#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
MARKER = ".tiny_e2e_generated"
PROJECT_ID = "tiny_allene_review"

CHECKPOINTS = [
    ("Library", "Mock registry and metadata are ready for review."),
    ("Discovery", "Discovery candidates are ready for review."),
    ("Matrix", "Literature matrix and outline are ready for review."),
    ("Blueprint", "Section blueprint is ready for review."),
    ("Sections", "Section draft is ready for review."),
    ("Figures", "Figure manifest is ready for review."),
    ("Draft", "First draft is ready for review."),
    ("Final", "Final audit and quality gate are ready for review."),
    ("Export", "Markdown export is ready for review."),
]


def main() -> int:
    args = parse_args()
    demo_root = args.demo_root.resolve()
    output_root = args.output_root.resolve()
    try:
        run_demo(demo_root, output_root, strict=args.strict)
    except DemoError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    print(f"tiny-e2e: wrote offline demo to {output_root}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run tiny offline end-to-end review-writer demo.")
    parser.add_argument("--demo-root", type=Path, default=Path("demo_projects/tiny_allene_review"))
    parser.add_argument("--output-root", type=Path, default=Path("/tmp/review_writer_tiny_e2e"))
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def run_demo(demo_root: Path, output_root: Path, *, strict: bool) -> None:
    if not demo_root.exists():
        raise DemoError(f"demo root not found: {demo_root}")
    prepare_output_root(output_root)
    inputs = demo_root / "inputs"
    registry_rows = load_registry(inputs / "paper_registry.jsonl")
    metadata = [load_json(inputs / row["metadata_path"]) for row in registry_rows]
    checkpoint_log = build_checkpoint_log()

    write_json(output_root / "project_status_before.json", {"project_id": PROJECT_ID, "exists": False, "mode": "tiny_offline_demo"})
    write_json(output_root / "checkpoint_log.json", {"project_id": PROJECT_ID, "checkpoints": checkpoint_log})
    write_checkpoint_md(output_root / "checkpoint_log.md", checkpoint_log)

    write_discovery(output_root, metadata)
    write_matrix_outline(output_root, metadata)
    write_blueprint(output_root, metadata)
    write_section_draft(output_root, metadata)
    write_figures(output_root, demo_root, metadata)
    final_draft = write_first_draft(output_root, metadata)
    write_final_audit(output_root, final_draft, strict=strict)
    write_export(output_root, final_draft)
    (output_root / MARKER).write_text("generated by scripts/demo/run_tiny_e2e.py\n", encoding="utf-8")


def prepare_output_root(output_root: Path) -> None:
    if output_root.exists():
        if (output_root / MARKER).exists():
            shutil.rmtree(output_root)
        elif any(output_root.iterdir()):
            raise DemoError(f"refusing to overwrite non-demo output root: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)


def load_registry(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise DemoError(f"registry not found: {path}")
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    if len(rows) != 3:
        raise DemoError(f"tiny demo expects 3 registry rows, got {len(rows)}")
    return rows


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise DemoError(f"metadata not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def write_discovery(output_root: Path, metadata: list[dict[str, Any]]) -> None:
    out = output_root / "00_discovery"
    out.mkdir(parents=True, exist_ok=True)
    candidates = [
        {
            "paper_id": row["paper_id"],
            "title": row["title"],
            "year": row["year"],
            "topic_tags": row["topic_tags"],
            "score": round(0.91 - index * 0.07, 2),
            "checkpoint_status": "approved_mock",
        }
        for index, row in enumerate(metadata)
    ]
    write_json(out / "discovery_candidates.json", {"topic": "allene-based chiral ligands", "candidates": candidates})
    write_json(out / "human_check_state.json", {"confirmed": True, "status": "approved_mock"})


def write_matrix_outline(output_root: Path, metadata: list[dict[str, Any]]) -> None:
    out = output_root / "01_matrix_outline"
    out.mkdir(parents=True, exist_ok=True)
    rows = []
    for index, row in enumerate(metadata, start=1):
        rows.append(
            {
                "ref_id": index,
                "paper_id": row["paper_id"],
                "title": row["title"],
                "year": row["year"],
                "method_tags": row["method_tags"],
                "key_findings": row["key_findings"],
            }
        )
    write_json(out / "literature_matrix.json", {"rows": rows, "checkpoint_status": "approved_mock"})
    outline = "\n".join(
        [
            "# Tiny Allene Review Outline",
            "",
            "## Ligand Design Motifs",
            "Compare allene ligand donor patterns and steric motifs.",
            "",
            "## Mock Selectivity Trends",
            "Summarize the synthetic trends from the three demo records.",
            "",
        ]
    )
    (out / "outline.md").write_text(outline, encoding="utf-8")
    write_json(out / "human_check.json", {"confirmed": True, "status": "approved_mock"})


def write_blueprint(output_root: Path, metadata: list[dict[str, Any]]) -> None:
    blueprint = {
        "project_id": PROJECT_ID,
        "checkpoint_status": "approved_mock",
        "sections": [
            {
                "section_id": "section_1",
                "title": "Ligand Design Motifs and Mock Selectivity Trends",
                "paper_ids": [row["paper_id"] for row in metadata],
                "expected_claim": "Allene ligand geometry and donor pattern jointly shape mock enantioselectivity trends.",
            }
        ],
    }
    write_json(output_root / "section_blueprint.json", blueprint)
    write_json(output_root / "01_matrix_outline" / "section_blueprint.json", blueprint)


def write_section_draft(output_root: Path, metadata: list[dict[str, Any]]) -> None:
    out = output_root / "02_section_drafting"
    out.mkdir(parents=True, exist_ok=True)
    section = "\n".join(
        [
            "## Ligand Design Motifs and Mock Selectivity Trends",
            "",
            "The tiny demo matrix links allene ligand geometry to three synthetic selectivity observations [1-3]. "
            "The phosphine record emphasizes axial rigidity [1], the P,N donor record emphasizes coordination geometry [2], "
            "and the palladium coupling record emphasizes steric pocket matching [3].",
            "",
        ]
    )
    (out / "section_1.md").write_text(section, encoding="utf-8")
    write_json(
        out / "section_tasks.json",
        {"sections": [{"section_id": "section_1", "title": "Ligand Design Motifs and Mock Selectivity Trends"}]},
    )
    write_json(out / "section_drafts.json", {"section_1": section})
    write_json(out / "human_check.json", {"confirmed": True, "status": "approved_mock"})
    write_json(
        out / "figure_candidates.json",
        {"figures": [{"figure_id": "tiny_fig_1", "source_path": "../03_figure_redraw/allene_placeholder.svg"}]},
    )


def write_figures(output_root: Path, demo_root: Path, metadata: list[dict[str, Any]]) -> None:
    out = output_root / "03_figure_redraw"
    out.mkdir(parents=True, exist_ok=True)
    source = demo_root / "inputs/figures/allene_placeholder.svg"
    target = out / "allene_placeholder.svg"
    shutil.copyfile(source, target)
    manifest = {
        "status": "approved_mock",
        "figures": [
            {
                "figure_id": "tiny_fig_1",
                "caption": "Mock design map for allene-based chiral ligands.",
                "source_path": "allene_placeholder.svg",
                "redrawn_image": "allene_placeholder.svg",
                "source_paper_ids": [row["paper_id"] for row in metadata],
            }
        ],
    }
    write_json(out / "figure_manifest.json", manifest)
    write_json(out / "redrawn_figure_manifest.json", manifest)
    write_json(out / "human_check.json", {"confirmed": True, "status": "approved_mock"})


def write_first_draft(output_root: Path, metadata: list[dict[str, Any]]) -> Path:
    out = output_root / "04_first_draft"
    out.mkdir(parents=True, exist_ok=True)
    references = build_references(metadata)
    draft = "\n".join(
        [
            "# Allene-Based Chiral Ligands in Asymmetric Catalysis",
            "",
            "## Ligand Design Motifs and Mock Selectivity Trends",
            "",
            "This tiny offline demo summarizes three synthetic metadata records about allene-based chiral ligands [1-3]. "
            "The mock evidence links axial rigidity, donor pattern, and steric pocket size to asymmetric catalysis trends.",
            "",
            "![Mock design map for allene-based chiral ligands](../03_figure_redraw/allene_placeholder.svg)",
            "",
            "Figure 1. Mock design map for allene-based chiral ligands.",
            "",
            "The phosphine example highlights rigidity in a synthetic allylation benchmark [1]. "
            "The P,N ligand example highlights coordination geometry in a copper addition setting [2]. "
            "The palladium example highlights steric matching in a coupling setting [3].",
            "",
            "## References",
            "",
            *references,
            "",
        ]
    )
    path = out / "final_draft.md"
    path.write_text(draft, encoding="utf-8")
    (out / "first_draft.md").write_text(draft, encoding="utf-8")
    write_json(out / "draft_bundle.json", {"draft_path": str(path), "checkpoint_status": "approved_mock"})
    write_json(out / "human_check.json", {"confirmed": True, "status": "approved_mock"})
    return path


def write_final_audit(output_root: Path, draft_path: Path, *, strict: bool) -> None:
    out = output_root / "05_final_audit"
    out.mkdir(parents=True, exist_ok=True)
    final_draft = out / "final_draft.md"
    shutil.copyfile(draft_path, final_draft)
    quality_json = out / "quality_report.json"
    quality_md = out / "quality_report.md"
    validator = REPO_ROOT / "scripts/validators/validate_review_quality.py"
    cmd = [
        sys.executable,
        str(validator),
        "--draft",
        str(final_draft),
        "--figure-manifest",
        str(output_root / "03_figure_redraw/figure_manifest.json"),
        "--judge-mode",
        "offline",
        "--output-json",
        str(quality_json),
        "--output-md",
        str(quality_md),
    ]
    if strict:
        cmd.append("--strict")
    result = subprocess.run(cmd, cwd=REPO_ROOT, text=True, capture_output=True, check=False)
    if result.returncode not in {0, 1}:
        raise DemoError(f"quality validator failed: {result.stderr.strip() or result.stdout.strip()}")
    quality = json.loads(quality_json.read_text(encoding="utf-8"))
    report = {
        "project_id": PROJECT_ID,
        "checkpoint_status": "approved_mock",
        "quality_status": quality.get("status"),
        "quality_errors": len(quality.get("errors") or []),
        "quality_warnings": len(quality.get("warnings") or []),
        "final_quality_gate_enforced": True,
        "network": "not_used",
        "qwen": "not_called",
        "mineru": "not_called",
        "pdf_body_read": "not_read",
    }
    write_json(out / "final_audit_report.json", report)
    write_json(out / "human_check.json", {"confirmed": True, "status": "approved_mock"})


def write_export(output_root: Path, final_draft: Path) -> None:
    out = output_root / "export"
    out.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(output_root / "05_final_audit/final_draft.md", out / "final_draft.md")
    write_json(out / "export_report.json", {"format": "markdown", "checkpoint_status": "approved_mock"})


def build_references(metadata: list[dict[str, Any]]) -> list[str]:
    refs = []
    for index, row in enumerate(metadata, start=1):
        authors = ", ".join(row["authors"])
        doi = row.get("doi") or "mock DOI unavailable"
        refs.append(f"[{index}] {authors}. {row['title']}. {row['journal']} {row['year']}. DOI: {doi}.")
    return refs


def build_checkpoint_log() -> list[dict[str, Any]]:
    return [
        {
            "index": index,
            "checkpoint": name,
            "states": ["blocked", "ready_for_human_review", "approved_mock"],
            "status": "approved_mock",
            "note": note,
        }
        for index, (name, note) in enumerate(CHECKPOINTS, start=1)
    ]


def write_checkpoint_md(path: Path, checkpoints: list[dict[str, Any]]) -> None:
    lines = ["# Tiny Demo Checkpoint Log", "", "| # | checkpoint | status |", "| --- | --- | --- |"]
    for row in checkpoints:
        lines.append(f"| {row['index']} | {row['checkpoint']} | {row['status']} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


class DemoError(Exception):
    pass


if __name__ == "__main__":
    raise SystemExit(main())
