#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
PROJECT_ID = "clean_3paper_allene_review"
MARKER = ".clean_3paper_e2e_generated"
TOP3 = ["F3I", "F47A", "P403"]

CHECKPOINTS = [
    ("Library", "Clean draft input package is ready for human review."),
    ("Discovery", "Approved Top 3 discovery candidates are ready for human review."),
    ("Matrix", "Clean draft literature matrix and outline are ready for human review."),
    ("Blueprint", "Section plan is ready for human review."),
    ("Sections", "Section draft is ready for human review."),
    ("Figures", "Figure note manifest is ready for human review."),
    ("Draft", "Clean draft manuscript is ready for human review."),
    ("Final", "Final audit and quality gate are ready for human review."),
    ("Export", "Markdown export is ready for human review."),
]


class CleanE2EError(Exception):
    pass


def main() -> int:
    args = parse_args()
    try:
        run_clean_e2e(args.demo_root.resolve(), args.output_root.resolve(), strict=args.strict)
    except CleanE2EError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    print(f"clean-3paper-e2e: wrote vertical slice to {args.output_root.resolve()}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run clean 3-paper offline vertical-slice E2E.")
    parser.add_argument("--demo-root", type=Path, default=Path("demo_projects/clean_3paper_allene_review"))
    parser.add_argument("--output-root", type=Path, default=Path("/tmp/review_writer_clean_3paper_e2e"))
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def run_clean_e2e(demo_root: Path, output_root: Path, *, strict: bool) -> None:
    if not demo_root.exists():
        raise CleanE2EError(f"demo root not found: {demo_root}")
    inputs = demo_root / "inputs"
    expected = demo_root / "expected"
    papers = load_clean_papers(inputs, expected)
    write_clean_input_package(demo_root, papers)
    prepare_output_root(output_root)
    write_project_status(output_root, demo_root, papers)
    write_json(output_root / "checkpoint_log.json", {"project_id": PROJECT_ID, "checkpoints": build_checkpoint_log()})
    write_discovery(output_root, papers)
    write_matrix_outline(output_root, papers)
    write_blueprint(output_root, papers)
    write_section(output_root, papers)
    write_figures(output_root, papers)
    draft_path = write_first_draft(output_root, papers)
    write_final_audit(output_root, draft_path, papers, strict=strict)
    write_eval_placeholder(output_root)
    write_export(output_root)
    write_run_summary(output_root, demo_root, papers)
    (output_root / MARKER).write_text("generated by scripts/demo/run_clean_3paper_e2e.py\n", encoding="utf-8")


def load_clean_papers(inputs: Path, expected: Path) -> list[dict[str, Any]]:
    selected = load_json(inputs / "selected_papers.verified_draft.json")
    bibliography = load_json(inputs / "bibliography_verification_summary.json")
    claims_payload = load_json(expected / "expected_claims.draft.json")
    figures_payload = load_json(expected / "expected_figures.draft.json")
    selected_rows = selected.get("papers") or []
    bibliography_rows = {row["candidate_id"]: row for row in bibliography.get("papers") or []}
    claims_by_id = group_by(claims_payload.get("claims") or [], "paper_id")
    figures_by_id = group_by(figures_payload.get("figure_notes") or [], "paper_id")
    if [row.get("candidate_id") for row in selected_rows] != TOP3:
        raise CleanE2EError("selected clean draft does not contain expected Top 3")
    papers: list[dict[str, Any]] = []
    for row in selected_rows:
        paper_id = row["candidate_id"]
        biblio = bibliography_rows.get(paper_id, {})
        claims = claims_by_id.get(paper_id, [])
        figures = figures_by_id.get(paper_id, [])
        if row.get("human_verified") is not False or row.get("needs_human_review") is not True:
            raise CleanE2EError(f"{paper_id}: clean draft must remain human_verified=false and needs_human_review=true")
        papers.append(
            {
                "paper_id": paper_id,
                "filename": row.get("filename") or biblio.get("filename"),
                "title": biblio.get("verified_title_draft") or row.get("title_draft") or paper_id,
                "authors": biblio.get("authors_draft") or row.get("authors_draft") or [],
                "year": biblio.get("year_draft") or row.get("year_draft") or "unknown",
                "journal": biblio.get("journal_draft") or row.get("journal_draft") or "unknown",
                "doi": biblio.get("doi_draft") or row.get("doi_draft") or "unknown",
                "role": row.get("role") or "unknown",
                "metadata_confidence": biblio.get("metadata_confidence") or row.get("metadata_confidence") or "low",
                "source_conflicts": biblio.get("conflicts") or row.get("source_conflicts") or [],
                "missing_fields": biblio.get("missing_fields") or row.get("missing_fields") or [],
                "claims": claims,
                "figure_notes": figures,
                "verification_status": "clean_draft",
                "human_verified": False,
                "needs_human_review": True,
            }
        )
    return papers


def write_clean_input_package(demo_root: Path, papers: list[dict[str, Any]]) -> None:
    inputs = demo_root / "inputs"
    claims_dir = inputs / "claims"
    claims_dir.mkdir(parents=True, exist_ok=True)
    clean_rows = []
    for paper in papers:
        clean_row = {
            "paper_id": paper["paper_id"],
            "candidate_id": paper["paper_id"],
            "title": paper["title"],
            "authors": paper["authors"] or "unknown",
            "year": paper["year"],
            "journal": paper["journal"],
            "doi": paper["doi"],
            "role": paper["role"],
            "verification_status": "clean_draft",
            "human_verified": False,
            "needs_human_review": True,
            "metadata_confidence": paper["metadata_confidence"],
            "source_conflicts": paper["source_conflicts"],
            "missing_fields": paper["missing_fields"],
            "claims_path": f"inputs/claims/{paper['paper_id']}.claims.draft.json",
            "figure_notes_path": f"inputs/figure_notes/{paper['paper_id']}.figure_notes.md",
        }
        clean_rows.append(clean_row)
        write_json(
            claims_dir / f"{paper['paper_id']}.claims.draft.json",
            {
                "paper_id": paper["paper_id"],
                "claims": paper["claims"],
                "verification_status": "clean_draft",
                "human_verified": False,
                "needs_human_review": True,
                "trusted_for_scientific_quality": False,
            },
        )
    write_json(
        inputs / "selected_papers.clean_draft.json",
        {
            "dataset_id": "clean_3paper_allene_v1",
            "status": "clean_draft",
            "papers": clean_rows,
            "trusted_for_scientific_quality": False,
            "human_verified": False,
            "needs_human_review": True,
            "warnings": clean_warnings(papers),
            "safety": safety_markers(),
        },
    )
    lines = []
    for row in clean_rows:
        lines.append(json.dumps(row, ensure_ascii=False))
    (inputs / "clean_registry.jsonl").write_text("\n".join(lines) + "\n", encoding="utf-8")


def clean_warnings(papers: list[dict[str, Any]]) -> list[str]:
    warnings: list[str] = []
    for paper in papers:
        if paper["missing_fields"]:
            warnings.append(f"{paper['paper_id']}: missing fields: {', '.join(paper['missing_fields'])}")
        if paper["source_conflicts"]:
            warnings.append(f"{paper['paper_id']}: source conflicts require human review")
    return warnings


def prepare_output_root(output_root: Path) -> None:
    if output_root.exists():
        if (output_root / MARKER).exists():
            shutil.rmtree(output_root)
        elif any(output_root.iterdir()):
            raise CleanE2EError(f"refusing to overwrite non-clean-demo output root: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)


def write_project_status(output_root: Path, demo_root: Path, papers: list[dict[str, Any]]) -> None:
    write_json(
        output_root / "project_status_before.json",
        {
            "project_id": PROJECT_ID,
            "mode": "clean_3paper_vertical_slice",
            "demo_root": str(demo_root),
            "selected_count": len(papers),
            "clean_draft": True,
            "needs_human_review": True,
            "not_final_scientific_review": True,
            **safety_markers(),
        },
    )


def write_discovery(output_root: Path, papers: list[dict[str, Any]]) -> None:
    write_json(
        output_root / "00_discovery/discovery_candidates.json",
        {
            "topic": topic_text(),
            "status": "clean_draft",
            "candidates": [
                {
                    "paper_id": paper["paper_id"],
                    "title": paper["title"],
                    "role": paper["role"],
                    "metadata_confidence": paper["metadata_confidence"],
                    "needs_human_review": True,
                    "human_verified": False,
                }
                for paper in papers
            ],
        },
    )


def write_matrix_outline(output_root: Path, papers: list[dict[str, Any]]) -> None:
    rows = []
    for ref_id, paper in enumerate(papers, start=1):
        rows.append(
            {
                "ref_id": ref_id,
                "paper_id": paper["paper_id"],
                "title": paper["title"],
                "authors": paper["authors"] or ["unknown"],
                "year": paper["year"],
                "journal": paper["journal"],
                "doi": paper["doi"],
                "role": paper["role"],
                "claim_count": len(paper["claims"]),
                "figure_note_count": len(paper["figure_notes"]),
                "missing_fields": paper["missing_fields"],
                "source_conflicts": paper["source_conflicts"],
                "needs_human_review": True,
                "human_verified": False,
            }
        )
    write_json(output_root / "01_matrix_outline/literature_matrix.json", {"rows": rows, "status": "clean_draft"})
    outline = "\n".join(
        [
            "# Clean 3-Paper Allene Review Outline",
            "",
            "## Background Anchor",
            "Use F3I only as a review/background draft anchor pending human review.",
            "",
            "## Representative Palladium Method",
            "Use F47A as a method draft anchor pending human review of the original paper.",
            "",
            "## Recent Progress Slot",
            "Use P403 as a recent-progress draft anchor while preserving missing authors/DOI warnings.",
            "",
        ]
    )
    write_text(output_root / "01_matrix_outline/outline.md", outline)


def write_blueprint(output_root: Path, papers: list[dict[str, Any]]) -> None:
    write_json(
        output_root / "section_blueprint.json",
        {
            "project_id": PROJECT_ID,
            "status": "clean_draft",
            "sections": [
                {
                    "section_id": "section_1",
                    "title": "Three-Paper Clean Draft Slice",
                    "paper_ids": [paper["paper_id"] for paper in papers],
                    "claims": [claim["claim_id"] for paper in papers for claim in paper["claims"]],
                    "figure_notes": [note["figure_note_id"] for paper in papers for note in paper["figure_notes"]],
                    "needs_human_review": True,
                }
            ],
        },
    )


def write_section(output_root: Path, papers: list[dict[str, Any]]) -> None:
    lines = [
        "## Three-Paper Clean Draft Slice",
        "",
        "This section is a clean_draft, needs_human_review, and not_final_scientific_review artifact. "
        "It organizes the approved Top 3 papers into background, representative method, and recent-progress roles [1-3].",
        "",
    ]
    for ref_id, paper in enumerate(papers, start=1):
        authors = authors_text(paper["authors"])
        claim_text = paper["claims"][0]["claim_text_draft"] if paper["claims"] else "Claim draft unavailable."
        lines.append(f"- [{ref_id}] {paper['paper_id']} ({authors}, {paper['year']}): {claim_text}")
    lines.extend(
        [
            "",
            "P403 retains missing authors/DOI warnings, and F47A/P403 source conflicts remain visible for human review.",
            "",
        ]
    )
    write_text(output_root / "02_section_drafting/section_1.md", "\n".join(lines))


def write_figures(output_root: Path, papers: list[dict[str, Any]]) -> None:
    out = output_root / "03_figure_redraw"
    out.mkdir(parents=True, exist_ok=True)
    svg = out / "clean_3paper_note_placeholder.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="760" height="380" viewBox="0 0 760 380">'
        '<rect width="760" height="380" fill="#f8fafc"/>'
        '<rect x="40" y="42" width="680" height="296" fill="#ffffff" stroke="#1f2937" stroke-width="2"/>'
        '<text x="68" y="98" font-family="Arial" font-size="28" fill="#111827">Clean 3-paper figure notes</text>'
        '<text x="68" y="148" font-family="Arial" font-size="20" fill="#374151">F3I: background concept note</text>'
        '<text x="68" y="188" font-family="Arial" font-size="20" fill="#374151">F47A: Pd asymmetric allene method note</text>'
        '<text x="68" y="228" font-family="Arial" font-size="20" fill="#374151">P403: recent phosphine oxide method note</text>'
        '<text x="68" y="282" font-family="Arial" font-size="18" fill="#6b7280">Placeholder only; no source image copied.</text>'
        "</svg>\n",
        encoding="utf-8",
    )
    figures = []
    for index, paper in enumerate(papers, start=1):
        note = paper["figure_notes"][0] if paper["figure_notes"] else {}
        figures.append(
            {
                "figure_id": f"clean_3paper_fig_{index}",
                "paper_id": paper["paper_id"],
                "caption": note.get("note_draft") or f"Figure note draft for {paper['paper_id']}",
                "source_path": "clean_3paper_note_placeholder.svg",
                "redrawn_image": "clean_3paper_note_placeholder.svg",
                "figure_or_scheme_label": note.get("figure_or_scheme_label", "unknown"),
                "source": note.get("source", "needs_manual_extraction"),
                "copied_source_image": False,
                "needs_human_review": True,
                "human_verified": False,
            }
        )
    write_json(out / "figure_manifest.json", {"status": "clean_draft", "figures": figures, "copied_source_images": False})


def write_first_draft(output_root: Path, papers: list[dict[str, Any]]) -> Path:
    refs = references(papers)
    lines = [
        "# Clean 3-Paper Allene Review Draft",
        "",
        "Status markers: clean_draft; needs_human_review; not_final_scientific_review.",
        "",
        "## Three-Paper Vertical Slice",
        "",
        "This draft arranges three approved allene papers into a compact vertical slice. "
        "F3I supplies a background anchor, F47A supplies a representative palladium asymmetric allene method, and P403 supplies a recent-progress phosphine oxide allenylation slot [1-3].",
        "",
        "![Clean 3-paper figure note placeholder](../03_figure_redraw/clean_3paper_note_placeholder.svg)",
        "",
        "Figure 1. Clean 3-paper figure note placeholder. It is not a copied source figure; source figure selection still needs human review.",
        "",
        "The current claim set is intentionally conservative. F3I is used for background framing, F47A for an axially chiral allene method signal, and P403 for a recent Pd-catalyzed asymmetric allenylation signal [1-3]. "
        "P403 still has missing authors and article DOI in the committed draft, so the final scientific review must wait for manual correction.",
        "",
        "## Human Review Required",
        "",
        "All claims and figure notes remain draft items. The reviewer must confirm paper-body support, exact figure or scheme labels, and bibliographic conflicts before scientific use.",
        "",
        "## References",
        "",
        *refs,
        "",
    ]
    path = output_root / "04_first_draft/final_draft.md"
    write_text(path, "\n".join(lines))
    return path


def references(papers: list[dict[str, Any]]) -> list[str]:
    rows = []
    for ref_id, paper in enumerate(papers, start=1):
        authors = authors_text(paper["authors"])
        doi = paper["doi"] if paper["doi"] and paper["doi"] != "unknown" else "needs human review"
        rows.append(f"[{ref_id}] {authors}. {paper['title']}. {paper['journal']} {paper['year']}. DOI: {doi}.")
    return rows


def write_final_audit(output_root: Path, draft_path: Path, papers: list[dict[str, Any]], *, strict: bool) -> None:
    out = output_root / "05_final_audit"
    out.mkdir(parents=True, exist_ok=True)
    final_draft = out / "final_draft.md"
    shutil.copyfile(draft_path, final_draft)
    quality_json = out / "quality_report.json"
    quality_md = out / "quality_report.md"
    cmd = [
        sys.executable,
        str(REPO_ROOT / "scripts/validators/validate_review_quality.py"),
        "--draft",
        str(final_draft),
        "--figure-manifest",
        str(output_root / "03_figure_redraw/figure_manifest.json"),
        "--judge-mode",
        "offline",
        "--output-json",
        str(quality_json),
        "--output-md",
        str(quality_md),
    ]
    result = subprocess.run(cmd, cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if result.returncode not in {0, 1}:
        raise CleanE2EError(f"quality validator failed: {result.stderr.strip() or result.stdout.strip()}")
    quality = load_json(quality_json)
    warnings = list(quality.get("warnings") or [])
    for paper in papers:
        if paper["missing_fields"]:
            warnings.append({"rule_id": "CLEAN3_METADATA_WARNING", "paper_id": paper["paper_id"], "message": f"missing fields: {', '.join(paper['missing_fields'])}"})
        if paper["source_conflicts"]:
            warnings.append({"rule_id": "CLEAN3_SOURCE_CONFLICT", "paper_id": paper["paper_id"], "message": "source conflicts require human review"})
    quality["warnings"] = warnings
    quality["status"] = "warn" if warnings and quality.get("status") == "pass" else quality.get("status", "warn")
    quality["trusted_for_scientific_quality"] = False
    write_json(quality_json, quality)
    write_quality_markdown(quality_md, quality)
    errors = quality.get("errors") or []
    if strict and errors:
        raise CleanE2EError(f"quality gate has critical errors: {len(errors)}")
    write_json(
        out / "final_audit_report.json",
        {
            "project_id": PROJECT_ID,
            "quality_status": quality.get("status"),
            "quality_errors": len(errors),
            "quality_warnings": len(warnings),
            "final_quality_gate_enforced": True,
            "clean_draft": True,
            "needs_human_review": True,
            "not_final_scientific_review": True,
            "trusted_for_scientific_quality": False,
            **safety_markers(),
        },
    )
    write_review_pack(out / "clean_3paper_review_pack.md", papers, quality)


def write_quality_markdown(path: Path, quality: dict[str, Any]) -> None:
    lines = ["# Clean 3-Paper Quality Report", "", f"- status: {quality.get('status')}", ""]
    if quality.get("warnings"):
        lines.append("## Warnings")
        for item in quality["warnings"]:
            lines.append(f"- {item}")
    lines.append("")
    lines.append("trusted_for_scientific_quality: false")
    write_text(path, "\n".join(lines))


def write_review_pack(path: Path, papers: list[dict[str, Any]], quality: dict[str, Any]) -> None:
    lines = [
        "# Clean 3-Paper Review Pack",
        "",
        "Status: clean_draft; needs_human_review; not_final_scientific_review.",
        "",
        "## Papers",
    ]
    for paper in papers:
        lines.extend(
            [
                f"### {paper['paper_id']}",
                f"- title: {paper['title']}",
                f"- authors: {authors_text(paper['authors'])}",
                f"- year/journal/doi: {paper['year']} / {paper['journal']} / {paper['doi']}",
                f"- missing_fields: {', '.join(paper['missing_fields']) or 'none'}",
                f"- source_conflicts: {len(paper['source_conflicts'])}",
                "- human_verified: false",
                "- needs_human_review: true",
                "",
                "Claim drafts:",
            ]
        )
        for claim in paper["claims"]:
            lines.append(f"- {claim['claim_id']}: {claim['claim_text_draft']} ({claim['confidence']})")
        lines.append("")
    lines.extend(["## Quality Gate", "", f"- status: {quality.get('status')}", f"- warnings: {len(quality.get('warnings') or [])}", ""])
    write_text(path, "\n".join(lines))


def write_eval_placeholder(output_root: Path) -> None:
    out = output_root / "eval"
    out.mkdir(parents=True, exist_ok=True)
    write_json(out / "clean_3paper_eval_report.json", {"status": "pending", "score_total": 0})
    write_text(out / "clean_3paper_eval_report.md", "# Clean 3-Paper Eval Report\n\nPending `run_clean_3paper_eval.py`.\n")


def write_export(output_root: Path) -> None:
    out = output_root / "export"
    out.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(output_root / "05_final_audit/final_draft.md", out / "final_draft.md")


def write_run_summary(output_root: Path, demo_root: Path, papers: list[dict[str, Any]]) -> None:
    write_json(
        output_root / "run_summary.json",
        {
            "project_id": PROJECT_ID,
            "demo_root": str(demo_root),
            "selected_papers": [paper["paper_id"] for paper in papers],
            "clean_draft": True,
            "needs_human_review": True,
            "not_final_scientific_review": True,
            "trusted_for_scientific_quality": False,
            "warnings": clean_warnings(papers),
            **safety_markers(),
        },
    )


def build_checkpoint_log() -> list[dict[str, Any]]:
    rows = []
    for index, (name, note) in enumerate(CHECKPOINTS, start=1):
        rows.append(
            {
                "index": index,
                "checkpoint": name,
                "name": name,
                "status": "approved_mock",
                "states": ["blocked", "ready_for_human_review", "approved_mock"],
                "human_review_required": True,
                "input_files": checkpoint_inputs(name),
                "output_files": checkpoint_outputs(name),
                "note": note,
            }
        )
    return rows


def checkpoint_inputs(name: str) -> list[str]:
    return {
        "Library": ["inputs/selected_papers.clean_draft.json", "inputs/clean_registry.jsonl"],
        "Discovery": ["inputs/verified_metadata/*.json"],
        "Matrix": ["00_discovery/discovery_candidates.json"],
        "Blueprint": ["01_matrix_outline/literature_matrix.json", "01_matrix_outline/outline.md"],
        "Sections": ["section_blueprint.json"],
        "Figures": ["expected/expected_figures.draft.json", "02_section_drafting/section_1.md"],
        "Draft": ["02_section_drafting/section_1.md", "03_figure_redraw/figure_manifest.json"],
        "Final": ["04_first_draft/final_draft.md"],
        "Export": ["05_final_audit/final_draft.md", "05_final_audit/quality_report.json"],
    }[name]


def checkpoint_outputs(name: str) -> list[str]:
    return {
        "Library": ["project_status_before.json"],
        "Discovery": ["00_discovery/discovery_candidates.json"],
        "Matrix": ["01_matrix_outline/literature_matrix.json", "01_matrix_outline/outline.md"],
        "Blueprint": ["section_blueprint.json"],
        "Sections": ["02_section_drafting/section_1.md"],
        "Figures": ["03_figure_redraw/figure_manifest.json"],
        "Draft": ["04_first_draft/final_draft.md"],
        "Final": ["05_final_audit/final_audit_report.json", "05_final_audit/quality_report.json", "05_final_audit/clean_3paper_review_pack.md"],
        "Export": ["export/final_draft.md"],
    }[name]


def safety_markers() -> dict[str, str]:
    return {
        "network": "not_used",
        "pdf_read": "not_used",
        "qwen": "not_used",
        "mineru_api": "not_used",
        "bailian": "not_used",
        "upload": "not_used",
        "knowledge_base": "not_created",
        "image_api": "not_used",
    }


def authors_text(authors: Any) -> str:
    if isinstance(authors, list) and authors:
        return ", ".join(str(item) for item in authors)
    if isinstance(authors, str) and authors and authors != "unknown":
        return authors
    return "Unknown authors"


def clean_warnings(papers: list[dict[str, Any]]) -> list[str]:
    warnings: list[str] = []
    for paper in papers:
        if paper["missing_fields"]:
            warnings.append(f"{paper['paper_id']}: missing fields: {', '.join(paper['missing_fields'])}")
        if paper["source_conflicts"]:
            warnings.append(f"{paper['paper_id']}: source conflicts require human review")
    return warnings


def group_by(rows: list[dict[str, Any]], key: str) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        grouped.setdefault(str(row.get(key)), []).append(row)
    return grouped


def topic_text() -> str:
    return "Clean 3-paper allene vertical slice"


def load_json(path: Path) -> Any:
    if not path.exists():
        raise CleanE2EError(f"required file not found: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CleanE2EError(f"invalid JSON: {path} ({exc})") from exc


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
