#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
MARKER = ".real_lite_e2e_generated"
PROJECT_ID = "real_lite_allene_review"
EXCERPT_CHARS = 650

CHECKPOINTS = [
    ("Library", "Selected real-lite package is ready for review."),
    ("Discovery", "Discovery candidates are ready for review."),
    ("Matrix", "Literature matrix and outline are ready for review."),
    ("Blueprint", "Section plan is ready for review."),
    ("Sections", "Section draft is ready for review."),
    ("Figures", "Figure pointer manifest is ready for review."),
    ("Draft", "First draft is ready for review."),
    ("Final", "Final audit and offline quality gate are ready for review."),
    ("Export", "Markdown export is ready for review."),
]


class DemoError(Exception):
    pass


def main() -> int:
    args = parse_args()
    try:
        run_demo(args.demo_root.resolve(), args.output_root.resolve(), strict=args.strict)
    except DemoError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    print(f"real-lite-e2e: wrote offline run to {args.output_root.resolve()}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run real-lite offline end-to-end review-writer demo.")
    parser.add_argument("--demo-root", type=Path, default=Path("demo_projects/real_lite_allene_review"))
    parser.add_argument("--output-root", type=Path, default=Path("/tmp/review_writer_real_lite_e2e"))
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def run_demo(demo_root: Path, output_root: Path, *, strict: bool) -> None:
    if not demo_root.exists():
        raise DemoError(f"demo root not found: {demo_root}")
    inputs = demo_root / "inputs"
    selected = load_selected(inputs / "selected_papers.json")
    if len(selected) < 3:
        raise DemoError(f"real-lite run expects at least 3 selected papers, got {len(selected)}")

    prepare_output_root(output_root)
    papers = [load_paper_bundle(inputs, row) for row in selected]
    checkpoint_log = build_checkpoint_log()

    write_json(
        output_root / "project_status_before.json",
        {
            "project_id": PROJECT_ID,
            "exists": False,
            "mode": "real_lite_offline_e2e",
            "selected_count": len(papers),
            "network": "not_used",
            "pdf_read": "not_used",
        },
    )
    write_json(output_root / "checkpoint_log.json", {"project_id": PROJECT_ID, "checkpoints": checkpoint_log})

    write_discovery(output_root, papers)
    write_matrix_outline(output_root, papers)
    write_blueprint(output_root, papers)
    write_section_draft(output_root, papers)
    write_figures(output_root, papers)
    draft_path = write_first_draft(output_root, papers)
    write_final_audit(output_root, draft_path, strict=strict)
    write_export(output_root)
    write_run_summary(output_root, demo_root, papers)
    (output_root / MARKER).write_text("generated by scripts/demo/run_real_lite_e2e.py\n", encoding="utf-8")


def prepare_output_root(output_root: Path) -> None:
    if output_root.exists():
        if (output_root / MARKER).exists():
            shutil.rmtree(output_root)
        elif any(output_root.iterdir()):
            raise DemoError(f"refusing to overwrite non-demo output root: {output_root}")
    output_root.mkdir(parents=True, exist_ok=True)


def load_selected(path: Path) -> list[dict[str, Any]]:
    payload = load_json(path, "selected_papers")
    selected = payload.get("selected_papers", payload if isinstance(payload, list) else [])
    if not isinstance(selected, list):
        raise DemoError("selected_papers must be a list")
    return [row for row in selected if isinstance(row, dict)]


def load_paper_bundle(inputs: Path, selected_row: dict[str, Any]) -> dict[str, Any]:
    paper_id = str(selected_row.get("paper_id") or "").strip()
    if not paper_id:
        raise DemoError("selected paper missing paper_id")
    metadata = load_json(inputs / "paper_metadata" / f"{paper_id}.metadata.json", f"{paper_id} metadata")
    content_pointer = load_json(inputs / "content_list" / f"{paper_id}.content_list.pointer.json", f"{paper_id} content pointer")
    figure_pointer = load_json(inputs / "figures" / f"{paper_id}.figures.pointer.json", f"{paper_id} figure pointer")
    excerpt_path = inputs / "mineru_markdown" / f"{paper_id}.excerpt.md"
    if not excerpt_path.exists():
        raise DemoError(f"excerpt not found: {excerpt_path}")
    excerpt = excerpt_path.read_text(encoding="utf-8", errors="ignore")[:EXCERPT_CHARS]
    return {
        "paper_id": paper_id,
        "selected": selected_row,
        "metadata": metadata,
        "excerpt_path": str(excerpt_path),
        "excerpt_preview": normalize_excerpt(excerpt),
        "content_pointer": content_pointer,
        "figure_pointer": figure_pointer,
        "title": clean_value(metadata.get("title")) or selected_row.get("title") or paper_id,
        "year": clean_value(metadata.get("year")) or selected_row.get("year") or "",
        "authors": clean_authors(clean_value(metadata.get("authors"))),
        "journal": clean_value(metadata.get("journal")) or "",
        "doi": clean_value(metadata.get("doi")) or "",
        "tags": clean_value(metadata.get("structured_tags")) or {},
    }


def load_json(path: Path, label: str) -> Any:
    if not path.exists():
        raise DemoError(f"{label} not found: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise DemoError(f"{label} is not valid JSON: {path} ({exc})") from exc


def clean_value(value: Any) -> Any:
    if isinstance(value, dict) and "value" in value:
        return clean_value(value["value"])
    if isinstance(value, list):
        return [clean_value(item) for item in value]
    return value


def clean_authors(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()][:6]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return ["Unknown authors"]


def normalize_excerpt(text: str) -> str:
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("<!--"):
            continue
        lines.append(stripped)
    preview = " ".join(lines)
    return " ".join(preview.split())[:EXCERPT_CHARS]


def write_discovery(output_root: Path, papers: list[dict[str, Any]]) -> None:
    candidates = []
    for index, paper in enumerate(papers):
        candidates.append(
            {
                "paper_id": paper["paper_id"],
                "title": paper["title"],
                "year": paper["year"],
                "score": round(0.94 - index * 0.03, 2),
                "has_metadata": True,
                "has_excerpt": True,
                "has_content_pointer": bool(paper["content_pointer"].get("source_path")),
                "has_figure_pointer": bool(paper["figure_pointer"].get("source_path")),
                "checkpoint_status": "approved_mock",
            }
        )
    write_json(output_root / "00_discovery/discovery_candidates.json", {"topic": topic_text(), "candidates": candidates})


def write_matrix_outline(output_root: Path, papers: list[dict[str, Any]]) -> None:
    rows = []
    for ref_id, paper in enumerate(papers, start=1):
        tags = paper.get("tags") if isinstance(paper.get("tags"), dict) else {}
        rows.append(
            {
                "ref_id": ref_id,
                "paper_id": paper["paper_id"],
                "title": paper["title"],
                "year": paper["year"],
                "journal": paper["journal"],
                "catalyst_or_method": tags.get("catalyst_or_method") or "",
                "reaction_type": tags.get("reaction_type") or "",
                "excerpt_preview": paper["excerpt_preview"],
            }
        )
    write_json(output_root / "01_matrix_outline/literature_matrix.json", {"rows": rows, "checkpoint_status": "approved_mock"})
    outline = "\n".join(
        [
            "# Real-Lite Allene Review Outline",
            "",
            "## Catalytic Entry Points For Allenyl Products",
            "Compare the selected palladium, copper, nickel, and gold examples.",
            "",
            "## Selectivity And Scope Signals",
            "Summarize scope and selectivity signals that can be audited by a human reviewer.",
            "",
        ]
    )
    (output_root / "01_matrix_outline").mkdir(parents=True, exist_ok=True)
    (output_root / "01_matrix_outline/outline.md").write_text(outline, encoding="utf-8")


def write_blueprint(output_root: Path, papers: list[dict[str, Any]]) -> None:
    write_json(
        output_root / "section_blueprint.json",
        {
            "project_id": PROJECT_ID,
            "checkpoint_status": "approved_mock",
            "sections": [
                {
                    "section_id": "section_1",
                    "title": "Catalytic Entry Points For Allenyl Products",
                    "paper_ids": [paper["paper_id"] for paper in papers],
                    "claim_to_check": "The selected records cover complementary catalytic entries to allene-containing products.",
                }
            ],
        },
    )


def write_section_draft(output_root: Path, papers: list[dict[str, Any]]) -> None:
    out = output_root / "02_section_drafting"
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        "## Catalytic Entry Points For Allenyl Products",
        "",
        "The selected real-lite records span palladium, copper, nickel, and gold catalysis in allene-centered synthesis [1-5]. "
        "They provide a compact trace of how propargylic substrates, allenamides, phosphorothioates, and allenyl phosphine oxides appear across the selected set.",
        "",
    ]
    for ref_id, paper in enumerate(papers, start=1):
        lines.append(
            f"- [{ref_id}] {paper['paper_id']} contributes a {paper.get('tags', {}).get('catalyst_or_method', 'catalytic')} example from {paper['year']}."
        )
    lines.append("")
    (out / "section_1.md").write_text("\n".join(lines), encoding="utf-8")


def write_figures(output_root: Path, papers: list[dict[str, Any]]) -> None:
    out = output_root / "03_figure_redraw"
    out.mkdir(parents=True, exist_ok=True)
    svg = out / "real_lite_pointer_placeholder.svg"
    svg.write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="720" height="360" viewBox="0 0 720 360">'
        '<rect width="720" height="360" fill="#f8fafc"/>'
        '<rect x="36" y="40" width="648" height="280" fill="#ffffff" stroke="#334155" stroke-width="2"/>'
        '<text x="60" y="95" font-family="Arial" font-size="28" fill="#0f172a">Real-lite figure pointer</text>'
        '<text x="60" y="145" font-family="Arial" font-size="20" fill="#334155">Selected papers: P410, P406, P405, P403, P401</text>'
        '<text x="60" y="195" font-family="Arial" font-size="20" fill="#334155">Placeholder only; no image API was called.</text>'
        '<text x="60" y="245" font-family="Arial" font-size="20" fill="#334155">Human review should choose source figures later.</text>'
        "</svg>\n",
        encoding="utf-8",
    )
    figures = [
        {
            "figure_id": "real_lite_fig_1",
            "caption": "Real-lite pointer map for selected allene synthesis records.",
            "source_path": "real_lite_pointer_placeholder.svg",
            "redrawn_image": "real_lite_pointer_placeholder.svg",
            "source_paper_ids": [paper["paper_id"] for paper in papers],
            "source_pointer_files": [f"inputs/figures/{paper['paper_id']}.figures.pointer.json" for paper in papers],
            "note": "Placeholder for QA only; source figures remain external and un-copied.",
        }
    ]
    write_json(out / "figure_manifest.json", {"status": "approved_mock", "figures": figures})


def write_first_draft(output_root: Path, papers: list[dict[str, Any]]) -> Path:
    out = output_root / "04_first_draft"
    out.mkdir(parents=True, exist_ok=True)
    references = build_references(papers)
    draft = "\n".join(
        [
            "# Real-Lite Allene Catalysis Review",
            "",
            "## Catalytic Entry Points For Allenyl Products",
            "",
            "This real-lite draft summarizes five selected records on allene-centered synthesis and catalysis [1-5]. "
            "The set includes palladium carbonylation, photoredox copper phosphorothiolation, a total synthesis case, asymmetric palladium allenylation, and nickel reductive coupling.",
            "",
            "![Real-lite pointer map for selected allene synthesis records](../03_figure_redraw/real_lite_pointer_placeholder.svg)",
            "",
            "Figure 1. Real-lite pointer map for selected allene synthesis records.",
            "",
            "Across the selected records, catalytic identity and substrate class are the main organizing variables. "
            "Palladium examples anchor carbonylation and asymmetric allenylation [1, 4], while copper, gold, and nickel records broaden the method set [2, 3, 5]. "
            "The current draft is intentionally compact and should be expanded only after human review of the selected source materials.",
            "",
            "## References",
            "",
            *references,
            "",
        ]
    )
    path = out / "final_draft.md"
    path.write_text(draft, encoding="utf-8")
    return path


def build_references(papers: list[dict[str, Any]]) -> list[str]:
    refs = []
    for ref_id, paper in enumerate(papers, start=1):
        authors = ", ".join(paper["authors"])
        doi = paper["doi"] or "not available in real-lite metadata"
        refs.append(f"[{ref_id}] {authors}. {paper['title']}. {paper['journal']} {paper['year']}. DOI: {doi}.")
    return refs


def write_final_audit(output_root: Path, draft_path: Path, *, strict: bool) -> None:
    out = output_root / "05_final_audit"
    out.mkdir(parents=True, exist_ok=True)
    final_draft = out / "final_draft.md"
    shutil.copyfile(draft_path, final_draft)
    quality_json = out / "quality_report.json"
    quality_md = out / "quality_report.md"
    validator = REPO_ROOT / "scripts/validators/validate_review_quality.py"
    cmd = [
        sys.executable,
        str(validator),
        "--draft",
        str(final_draft),
        "--figure-manifest",
        str(output_root / "03_figure_redraw/figure_manifest.json"),
        "--judge-mode",
        "offline",
        "--output-json",
        str(quality_json),
        "--output-md",
        str(quality_md),
    ]
    if strict:
        cmd.append("--strict")
    result = subprocess.run(cmd, cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if result.returncode not in {0, 1}:
        raise DemoError(f"quality validator failed: {result.stderr.strip() or result.stdout.strip()}")
    quality = json.loads(quality_json.read_text(encoding="utf-8"))
    errors = quality.get("errors") or []
    warnings = quality.get("warnings") or []
    figures = json.loads((output_root / "03_figure_redraw/figure_manifest.json").read_text(encoding="utf-8")).get("figures") or []
    if strict and (quality.get("status") == "fail" or errors):
        raise DemoError(f"quality gate failed with {len(errors)} errors")
    if strict and not figures:
        raise DemoError("figure manifest is empty")
    write_json(
        out / "final_audit_report.json",
        {
            "project_id": PROJECT_ID,
            "checkpoint_status": "approved_mock",
            "quality_status": quality.get("status"),
            "quality_errors": len(errors),
            "quality_warnings": len(warnings),
            "figure_manifest_empty": not bool(figures),
            "final_quality_gate_enforced": True,
            "judge_mode": "offline",
            "network": "not_used",
            "qwen": "not_used",
            "mineru_api": "not_used",
            "pdf_read": "not_used",
            "upload": "not_used",
        },
    )


def write_export(output_root: Path) -> None:
    out = output_root / "export"
    out.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(output_root / "05_final_audit/final_draft.md", out / "final_draft.md")


def write_run_summary(output_root: Path, demo_root: Path, papers: list[dict[str, Any]]) -> None:
    expected_files = [
        "project_status_before.json",
        "checkpoint_log.json",
        "00_discovery/discovery_candidates.json",
        "01_matrix_outline/literature_matrix.json",
        "01_matrix_outline/outline.md",
        "section_blueprint.json",
        "02_section_drafting/section_1.md",
        "03_figure_redraw/figure_manifest.json",
        "04_first_draft/final_draft.md",
        "05_final_audit/final_audit_report.json",
        "05_final_audit/quality_report.json",
        "export/final_draft.md",
        "run_summary.json",
    ]
    write_json(
        output_root / "run_summary.json",
        {
            "project_id": PROJECT_ID,
            "demo_root": str(demo_root),
            "selected_papers": [paper["paper_id"] for paper in papers],
            "selected_count": len(papers),
            "output_files": expected_files,
            "network": "not_used",
            "pdf_read": "not_used",
            "qwen": "not_used",
            "mineru_api": "not_used",
            "upload": "not_used",
            "knowledge_base": "not_used",
            "image_api": "not_used",
        },
    )


def build_checkpoint_log() -> list[dict[str, Any]]:
    rows = []
    for index, (name, note) in enumerate(CHECKPOINTS, start=1):
        rows.append(
            {
                "index": index,
                "checkpoint": name,
                "input_files": checkpoint_inputs(name),
                "output_files": checkpoint_outputs(name),
                "states": ["blocked", "ready_for_human_review", "approved_mock"],
                "status": "approved_mock",
                "human_review_required": True,
                "note": note,
            }
        )
    return rows


def checkpoint_inputs(name: str) -> list[str]:
    mapping = {
        "Library": ["inputs/selected_papers.json", "inputs/paper_registry.jsonl", "inputs/paper_metadata/*.json"],
        "Discovery": ["project_status_before.json", "inputs/mineru_markdown/*.excerpt.md"],
        "Matrix": ["00_discovery/discovery_candidates.json"],
        "Blueprint": ["01_matrix_outline/literature_matrix.json", "01_matrix_outline/outline.md"],
        "Sections": ["section_blueprint.json"],
        "Figures": ["inputs/figures/*.pointer.json", "02_section_drafting/section_1.md"],
        "Draft": ["02_section_drafting/section_1.md", "03_figure_redraw/figure_manifest.json"],
        "Final": ["04_first_draft/final_draft.md", "03_figure_redraw/figure_manifest.json"],
        "Export": ["05_final_audit/final_draft.md", "05_final_audit/quality_report.json"],
    }
    return mapping[name]


def checkpoint_outputs(name: str) -> list[str]:
    mapping = {
        "Library": ["project_status_before.json"],
        "Discovery": ["00_discovery/discovery_candidates.json"],
        "Matrix": ["01_matrix_outline/literature_matrix.json", "01_matrix_outline/outline.md"],
        "Blueprint": ["section_blueprint.json"],
        "Sections": ["02_section_drafting/section_1.md"],
        "Figures": ["03_figure_redraw/figure_manifest.json"],
        "Draft": ["04_first_draft/final_draft.md"],
        "Final": ["05_final_audit/final_audit_report.json", "05_final_audit/quality_report.json"],
        "Export": ["export/final_draft.md"],
    }
    return mapping[name]


def topic_text() -> str:
    return "Allene-based chiral ligands in asymmetric catalysis"


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
