from __future__ import annotations

AI_STATUSES = {
    "AI_EXTRACTED",
    "HUMAN_REVIEW_REQUIRED",
    "MISSING_SOURCE",
    "CONFLICT",
    "UNSUPPORTED_CANDIDATE",
}

FORBIDDEN_PHASE8A_STATUSES = {
    "VERIFIED",
    "REJECTED",
    "EDITED",
    "CANNOT_VERIFY",
}

CLAIM_SUPPORT_STATUSES = {
    "CANDIDATE_SUPPORTED",
    "PARTIALLY_SUPPORTED",
    "UNSUPPORTED_CANDIDATE",
    "CONFLICT",
    "MISSING_SOURCE",
    "HUMAN_REVIEW_REQUIRED",
}

MECHANISM_CLASSES = {
    "EXPERIMENTALLY_DEMONSTRATED",
    "AUTHOR_PROPOSED",
    "REVIEWER_INFERENCE_CANDIDATE",
    "AI_INFERENCE",
}

EVIDENCE_DIRECTNESS = {
    "DIRECT_NUMERIC",
    "DIRECT_TEXTUAL",
    "TABLE_SUPPORTED",
    "FIGURE_SUPPORTED",
    "AUTHOR_INTERPRETATION",
    "INDIRECT_CONTEXT",
}

REVIEW_ACTIONS = {
    "accept",
    "reject",
    "edit",
    "cannot_verify",
    "defer",
    "add_note",
}

